SELECT B.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(PRICE*SALES) AS TOTAL_SALES
FROM BOOK AS B, AUTHOR AS A, BOOK_SALES AS S
WHERE B.BOOK_ID = S.BOOK_ID AND A.AUTHOR_ID = B.AUTHOR_ID AND 
SALES_DATE LIKE '2022-01%'
GROUP BY B.AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC ;

