SELECT THREE_GEN.ID
FROM ECOLI_DATA AS ONE_GEN # 1세대

JOIN ECOLI_DATA AS TWO_GEN # 2세대
ON ONE_GEN.ID = TWO_GEN.PARENT_ID 

JOIN ECOLI_DATA AS THREE_GEN # 3세대 
ON TWO_GEN.ID = THREE_GEN.PARENT_ID

WHERE ONE_GEN.PARENT_ID IS NULL
ORDER BY THREE_GEN.ID