SELECT ECOLI_PER.ID,
CASE WHEN ECOLI_PER.PER <= 0.25 THEN 'CRITICAL'
WHEN ECOLI_PER.PER <= 0.5 THEN 'HIGH'
WHEN ECOLI_PER.PER <= 0.75 THEN 'MEDIUM'
ELSE 'LOW'
END AS COLONY_NAME
FROM(
    SELECT ID,
    PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS PER
    FROM ECOLI_DATA) AS ECOLI_PER
ORDER BY ECOLI_PER.ID
    